TDAT: public void test bug35610 ( ) throws exception {  <NL> create table ( " test bug35610 " , " ( field1 int , field2 int , field3 int ) " ) ;  <NL> this . stmt . execute update ( " insert into test bug35610 values ( 1 , 2 , 3 ) " ) ;  <NL> exercise35610 ( this . stmt , false ) ;  <NL> exercise35610 ( get connection with props ( " use column names in find column = true " ) . create statement ( ) , true ) ;  <NL>  }  COM: <s> tests fix for bug 35610 bug 35150 </s>