TDAT: public void test bind exception on connect1 ( ) throws exception {  <NL> socket channel channel1 = socket channel . open ( ) ;  <NL> socket channel channel2 = socket channel . open ( ) ;  <NL> channel1 . socket ( ) . set reuse address ( true ) ;  <NL> channel2 . socket ( ) . set reuse address ( true ) ;  <NL>  <NL> inet address loop back = inet address . get by name ( " 127 . 0 . 0 . 1 " ) ;  <NL> int port = 8000 ;  <NL> inet socket address addr1 = new inet socket address ( loop back , port ) ;  <NL> channel1 . socket ( ) . bind ( addr1 ) ;  <NL> channel2 . socket ( ) . bind ( addr1 ) ;  <NL>  <NL> channel1 . connect ( svr addr ) ;  <NL> try {  <NL> channel2 . connect ( svr addr ) ; / / results in bind exception <NL> fail ( " should have thrown a bind exception " ) ;  <NL>  } catch ( bind exception e ) {  <NL>  / / gulp <NL>  }  <NL> channel1 . close ( ) ;  <NL>  }  COM: <s> this tests bind exception is thrown on connect </s>