TDAT: public void test get by key failure not available after remove ( ) {  <NL> i entity fake = create test object ( 1 ) ;  <NL>  <NL> prepare create ( fake ) ;  <NL> replay ( factory ) ;  <NL>  <NL> container . create ( ) ;  <NL> container . remove ( fake ) ;  <NL>  <NL> try {  <NL> container . get ( fake . get key ( ) ) ;  <NL> fail ( ) ;  <NL>  } catch ( illegal argument exception expected ) {  <NL> assert equals ( " object with key " + fake . get key ( )  <NL>  + " is not contained in this container " , expected <NL>  . get message ( ) ) ;  <NL>  }  <NL>  }  COM: <s> tests that after an object is removed an exception is thrown when </s>