TDAT: public void test _ exceptions2 ( ) {  <NL> system . out . println ( " test _ exceptions2 output : " ) ;  <NL> int i = 2 ;  <NL> system . out . println ( " i : " + i ) ;  <NL>  / / obviously wrong <NL> fail ( " fail ( ) , with this test _ exceptions2 message " ) ;  <NL>  / / will the test execute this or exit with exception ?  <NL>  / / should not execute <NL> i = i * 10 ;  <NL> system . out . println ( " i : " + i ) ;  <NL>  }  COM: <s> test should fail with the fail message displayed </s>