TDAT: public void test release multiple times ( ) throws sql exception {  <NL> connection con = get connection ( ) ;  <NL> savepoint savepoint1 = con . set savepoint ( " my name " ) ;  <NL> con . release savepoint ( savepoint1 ) ;  <NL> try {  <NL> con . release savepoint ( savepoint1 ) ;  <NL> fail ( " fail 12 releasing a savepoint multiple times should fail " ) ;  <NL>  } catch ( sql exception se ) {  <NL>  / / expected exception .  <NL> assert sql state ( " 3b001 " , se ) ;  <NL>  }  <NL> con . rollback ( ) ;  <NL>  }  COM: <s> test 12 releasing a savepoint multiple times should not work </s>